import React from 'react'
import { Link } from 'react-router-dom'
import useFetch from '../hook/useFetch'


function PublicationsPage() {

  return (
    <div className='h-fit p-10 col-start-2 col-end-13 row-start-2 row-end-3 border-t-4 border-blue-900'>
      <div>
        <h2 className='text-gray-700 font-medium text-[50px]'>Publications</h2>
      </div>
      <div id='theses'>
        <h3 className='text-2xl font-medium'>Theses</h3>
        <ul className='p-5'>
          <li className='text-gray-700 mt-2'><span className='text-gray-800 font-medium'>Ph.D. Thesis:</span>A Semantic-Aware Authorization Model Based on Deontic Logic, Ph.D. Thesis (Supervisor: Dr Rasool Jalili), Department of Computer Engineering, Sharif University of Technology, Tehran, Iran, 2010 <Link to='/' className='text-blue-900 hover:font-medium'>[English-PDF]</Link>.</li>
          <li className='text-gray-700 mt-2'><span className='text-gray-800 font-medium'>M.Sc. Thesis:</span>A Semantic-Aware Authorization Model Based on Deontic Logic, Ph.D. Thesis (Supervisor: Dr Rasool Jalili), Department of Computer Engineering, Sharif University of Technology, Tehran, Iran, 2010 <Link to='/' className='text-blue-900 hover:font-medium'>[English-PDF]</Link>.</li>
          <li className='text-gray-700 mt-2'><span className='text-gray-800 font-medium'>B.Sc. Project:</span>A Semantic-Aware Authorization Model Based on Deontic Logic, Ph.D. Thesis (Supervisor: Dr Rasool Jalili), Department of Computer Engineering, Sharif University of Technology, Tehran, Iran, 2010 <Link to='/' className='text-blue-900 hover:font-medium'>[English-PDF]</Link>.</li>
        </ul>
      </div>
      <div>
        <h3 className='text-2xl font-medium'>Published Journal Papers</h3>
        <ol className='p-8 list-decimal'>
          <li className='text-gray-700 mt-2'>&nbsp; Shahrzadi, L.,<strong>Mansouri, A</strong> ., Alavi, M., &amp; Shabani, A. (2024).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.sciencedirect.com/science/article/pii/S2667096824000508" target="_blank"> Causes, Consequences, and Strategies to Deal with Information Overload: A Scoping Review</a>. International Journal of Information Management Data Insights, 4(2), 100261.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Ebrahimi Dorcheh, E.,<strong> Mansouri, A</strong>., Pashootanizadeh, M., Mirbagherifard, A. A., &amp; Shabani, A. (2024).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://academic.oup.com/rev/advance-article-abstract/doi/10.1093/reseval/rvae009/7613011" target="_blank"> Determining and Weighting Effective Outputs of Humanities Research to Meet Scientific and Professional Qoals: A study of Language and Literature Fields</a>. Research Evaluation, rvae009.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Dorcheh, E. E.,<strong> Mansouri, A</strong>., Pashootanizadeh, M., Mirbagherifard, A. A., &amp; Shabani, A. (2024).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://jscires.org/article/7019" target="_blank"> Determining and Prioritizing the Evaluation Criteria of Humanities Scientific Outputs: A Case Study of Language and Literature Fields</a>. Journal of Scientometric Research, 13(1), 148- 160.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Ebrahimi Dorcheh, E.,<strong>  Mansouri , A</strong>., Pashootanizadeh, M., Mirbagheri Fard, S. A. A., &amp; Shabani, A. (2023).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://rsci.shahed.ac.ir/article_3798.html?lang=en" target="_blank"> Harms and Strategies for Evaluating Humanities Research Outputs: A Case Study of Language and Literature</a>. Scientometrics Research Journal, 9(2),75- 96.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Ebrahimi Dorcheh, E.,<strong>  Mansouri , A</strong>., Pashootanizadeh, M., Mirbagerfard, A., Shabani, A.(2023).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://jipm.irandoc.ac.ir/article_705519_en.html?lang=en" target="_blank"> AEvaluation Policies and Criteria of Humanities Scientific Outputs from Experts' Point of View: A Case Study of Language and Literature Fields</a>. Iranian Journal of Information Processing and Management,[in Press].</li>
          <li className='text-gray-700 mt-2'>&nbsp; Kamani, M.,<strong>  Mansouri , A</strong>.(2023).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://rsci.shahed.ac.ir/article_4167_en.html?lang=en" target="_blank">Analysis The State Of Cooperation Between University And Industry From The Aspect Of Financial Support</a>. Scientometrics Research Journal.</li>
          <li className='text-gray-700 mt-2'>&nbsp;Fathi, M., Shabani, A., <strong> Mansouri , A</strong>.(2023).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://digitalcommons.unl.edu/libphilprac/7858?utm_source=digitalcommons.unl.edu%2Flibphilprac%2F7858&utm_medium=PDF&utm_campaign=PDFCoverPages" target="_blank">Metaversity and Metaworth, Two Important Prerequisites to Prepare for the Metaverse</a>.  Library Philosophy and Practice (e-journal),78585.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Zarmehr, F., <strong> Mansouri , A</strong>., Karshenas, H.(2023).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://jipm.irandoc.ac.ir/article_698598.html?lang=en" target="_blank">Comparison of the Performance of Approaches in Discovering and Extracting E-book Topics</a>.  Iranian Journal of Information Processing and Management,38(4), 1367- 1390.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong> Mansouri , A</strong>., Mohammadpour, M.(2023).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://ijism.isc.ac/article_705739.html" target="_blank">Determining Technology Life Cycle Prediction based on Patent Bibliometric Data</a>. International Journal of Information Science and Management (IJISM),21(3), 161- 185.</li>
          <li className='text-gray-700 mt-2'>&nbsp;Fadavi Hoseini, F. <strong> Mansouri , A</strong>.(2022).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.tandfonline.com/doi/full/10.1080/00987913.2022.2127403" target="_blank">The Role of Articles in Science–Technology Relationship: A Topic Analysis of Non-patent Literature (NPL) References</a>. Serials Review,48(1-2), 137- 150.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Zarmehr, F. <strong> Mansouri, A</strong>., &amp; Karshenas Najafabadi, H. (2022).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://jipm.irandoc.ac.ir/article_698598_en.html?lang=fa" target="_blank">comparison of the Performance of Approaches in Discovering and Extracting E-Book Topics</a>. Iranian Journal of Information Processing and Management,  38(4), 1369- 1393.</li>
          <li className='text-gray-700 mt-2'>&nbsp;  <strong> Mansouri , A</strong>., Ebrahimi Dorcheh, E. (2022).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://rsci.shahed.ac.ir/article_3855.html?lang=en" target="_blank">Success Factors in Research Activities Based on the Experiences of Top Researchers</a>. Scientometrics Research Journal .</li>
          <li className='text-gray-700 mt-2'>&nbsp; Akhavanhariri, E., <strong> Mansouri , A</strong>., &amp;  Karshenas Najafabadi. (2022).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://jipm.irandoc.ac.ir/article_698612.html" target="_blank">Identification of Hot Topics and Trends in Knowledge and Information Science, Based on Text Mining Techniques</a>.Iranian Journal of Information processing and Management,38(2), 35- 62</li>
          <li className='text-gray-700 mt-2'>&nbsp; Soleymani, N., <strong> Mansouri , A</strong>., Shabani, A., &amp; Seyadat, A. (2022).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://nastinfo.nlai.ir/article_2738.html?lang=en" target="_blank">Components of Research Data Management (RDM) in Academic Libraries</a>. Librarianship and Information Organization Studies, 23(1),20- 39. </li>
          <li className='text-gray-700 mt-2'>&nbsp; Torabi, M., Pashootanizade, M., &amp; <strong> Mansouri, A</strong>. (2021).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://infosci.um.ac.ir/article_40534.html?lang=en" target="_blank">Study of the Effective Factors on Technology Acceptance of Social Cataloging Apps by Postgraduate Students of Isfahan University Based on the UTAUT2 Mode</a>.Library and Information Science, 11(1), 300- 321. </li>
          <li className='text-gray-700 mt-2'>&nbsp; Dehkhodaei, R ;<strong> Mansouri ,A</strong>; &amp; Erfanmanesh, A. (2021).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://jks.atu.ac.ir/article_12535.html?lang=en" target="_blank"> Investigating of Publishing skills in Scholarly journals in PhD students of University of Isfahan</a>. Knowledge Retrieval and Semantic System, 7(26), 119- 142. </li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong> Mansouri, A</strong>., Zarmehr, F., &amp; Karshenas, H. (2020).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://hii.khu.ac.ir/article-1-2909-en.html" target="_blank">A Review of Text Mining Approaches and their Function in Discovering and Extracting a Topic</a>.Human Information Interaction, 7(1), 15- 26.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Zarmehr, F., <strong> Mansouri, A</strong>., &amp; Karshenas, H. (2020).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://infosci.um.ac.ir/article_40524.html?lang=en" target="_blank">Topic Modeling and its Application in Research: A Review of Specialized Literature</a>.Library and Information Science Research, 11(1),23- 39.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Baghmohammad, M.,<strong> Mansouri, A</strong>., &amp; Cheashmehsohrabi, M. (2020).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://jipm.irandoc.ac.ir/article-1-4480-en.html" target="_blank"> Identification of Topic Development Process of Knowledge and Information Science Field Based on the Topic modeling (LDA)</a>. Iranian Journal of Information Processing and Management, 36(2), 297– 328.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Zarmehr,F.,<strong> Mansouri, A</strong>., &amp; Kazemi, M. (2020). <a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://slis.scu.ac.ir/article_14285.html?lang=en" target="_blank">Investigating the Social Capital of Public Library organization of Iran, using the Social Network Analysis of the Scientific Communication of the Staff of this Organization</a>. Journal of Studies in Library and Information Science, 12(2).</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong> Mansouri, A</strong>., &amp; Salimian Rezie, M. (2019).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://slis.scu.ac.ir/article_12657_en.html" target="_blank"> Examines the Factors of Attraction and Development of Donor’s Participation in Library Building</a>. Journal of Studies in Library and Information Science, 26(2),2. </li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri, A</strong>., &amp; Soleymani Asl, N. (2019). <a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.emerald.com/insight/content/doi/10.1108/EL-10-2018-0204/full/html?journalCode=el&utm_source=TrendMD&utm_medium=cpc&utm_campaign=The_Electronic_Library_TrendMD_1&WT.mc_id=Emerald_TrendMD_1" target="_blank">Assessing Mobile Application Components in Providing Library Services</a>. Electronic Library, 37(1), 49- 66.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri,A</strong>,.Forouzandehshahraki,M;&amp;Erfanmanesh, A.(2018).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.magiran.com/paper/1890674?lang=en" target="_blank"> Status and Factors Associated with Citedness of Scholarly Outputs by Patents for the Type 1 Medical Science Universities in Iran during the Years 2000-2015</a>. Scientometrics Research Journal, 15(361), 126– 131.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri, A</strong>., Soheili, F., &amp; Ghazvineh, P. (2018).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href=" https://www.magiran.com/paper/2008578?lang=en" target="_blank">The Status of Scientific Poverty of Islamic Countries’ Researchers in Medical Sciences</a>. Scientometrics Research Journal, 4(8), 17– 32.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri, A</strong>., Javani, Z., &amp; Pashootanizadeh, M. (2017).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.magiran.com/paper/1669877?lang=en" target="_blank">A survey on the Present Condition of Medical Patents in Islamic Countries</a>. Library and Information Science, 13(652), 420– 425.</li>
          <li className='text-gray-700 mt-2'><strong>Mansouri, A</strong>., Mohammadpour, M., &amp; Hayati, S. (2017). <a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://lis.aqr-libjournal.ir/article_50528.html?lang=en" target="_blank">How to Detect the Life Cycle of Technology in the Domain of Endoscopy Based on the Hidden Markov Model</a>. Library and Information Sciences, 20(3), 95– 121. </li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri, A</strong>., &amp; Soheli, F.(2017).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href=" https://slis.scu.ac.ir/article_12267.html" target="_blank"> A survey on Lag Time in Forming Knowledge Flow in Islamic Countries Patents</a>. Journal of Studies in Library and Information Science, 9(21), 49– 70.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri, A</strong>., Tavakolizadeh Ravari, M.,  Makizadeh, F; &amp; Tusi, Z. (2017).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href=" https://jipm.irandoc.ac.ir/browse.php?a_id=3124&sid=1&slc_lang=en" target="_blank"> The Evolution of Technology; Case Study: Thematic Categories Analysis of RFID Patents</a>. Iranian Journal of Information Processing Management, 33(1), 299– 314.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Soheili, F., Rahimi, S., <strong> Mansouri,A </strong>., &amp; Tousi, Z. (2017).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://ijism.ricest.ac.ir/index.php/ijism/article/view/1057.html" target="_blank"> Studying the Application of Epidemic Theory in Transmission Cycle of Technology: A Case Study of Nanotechnology Patent</a>. International Journal of Information Science and Management, 15(2), 107– 121.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Soheili, F., &amp; <strong> Mansouri, A</strong>.(2016).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://nastinfo.nlai.ir/article_851.html" target="_blank"> The Value of Islamic Countries Patents based on Importance Factor</a>. National Studies on Librarianship and Information Organization, 27(2), 129– 148. </li>
          <li className='text-gray-700 mt-2'>&nbsp; Tavakolizade Ravari, M;<strong> Mansouri, A</strong>., Makizadeh, F; &amp; Tusi, Z. (2016).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href=" http://jipm.irandoc.ac.ir/article-1-2988-en.html&nbsp" target="_blank"> Epidemic Model of a Concept within the Subject Classes of Patents: A Case Study on the Term RFID</a>. Iranian Journal of Information Processing Management, 32(1), 75– 91.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Soheili, F., Khademi, R., <strong> &amp; Mansouri, A</strong>. (2015).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://ijism.ricest.ac.ir/index.php/ijism/article/view/501.html" target="_blank"> Correlation Between Impact Factor and Productivity with Centrality Measures in Journals of Information Science: A social Network Analysis</a>. International Journal of Information Science and Management, 13(1), 21– 38.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri, A</strong>., &amp; Osareh, F. (2014).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.researchgate.net/publication/287276048_Surveying_The_Value_of_Knowledge_Resources_Based_on_the_Importance_Factor_Backward-looking_Factor_Forward-looking_Factor_Case_Study_of_Patents.html" target="_blank"> Surveying the Value of Knowledge Resources Based on the Importance Factor (backward-looking factor, forward-looking factor): Case Study of Patents</a>. Iranian Journal of Information Processing Management, 29(3), 657- 684.</li>
          <li className='text-gray-700 mt-2'>&nbsp; Soheili, F., &amp;<strong>Mansouri,A</strong>.(2014).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://slis.scu.ac.ir/article_11307.html" target="_blank">The Analysis of the Iranian Chemistry Co-Authorship Network Using Centrality Measure</a>. Journal of Library and Information Science Studies, 21(13), 89– 106. </li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong> Mansouri,A</strong>., &amp; Osareh, F. (2013).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.sid.ir/en/journal/ViewPaper.aspx?ID=509935" target="_blank">  Knowledge Flow Among the Network of Inventors in Electricity &amp; Electronics</a>. Library and Information Science, 16(262), 143– 166.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri,A</strong>.(2010).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.magiran.com/paper/820126?lang=en" target="_blank"> Semantic Theory of Information</a>. Library and Information Science, 13(3), 101.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri,A</strong>., &amp; Osareh, F. (2010). <a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://nastinfo.nlai.ir/article_214_0.html?lang=en.html" target="_blank"> Leading Scientific Countries of the Islamic World in the Web of Science Database</a>.National Studies on Librarianship and Information Organization, 21(1), 146– 169.</li>
          <li className='text-gray-700 mt-2'>&nbsp; <strong>Mansouri,A</strong>. (2009).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://rjnsq.sinaweb.net/article_99644.html" target="_blank"> National Identity in Text Books: A Content Analysis of Farsi Text Books of Elementary Level</a>.National Studies, 10(38), 27– 46.</li>
          <li className='text-gray-700 mt-2'>&nbsp;<strong> Mansouri,A</strong>., &amp; Osareh, F. (2013).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.sid.ir/en/journal/ViewPaper.aspx?ID=509935" target="_blank">  Knowledge Flow Among the Network of Inventors in Electricity &amp; Electronics</a>. Library and Information Science, 16(262), 143– 166.</li>
          <li className='text-gray-700 mt-2'>&nbsp;<strong>Mansouri,A</strong>.(2010).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.magiran.com/paper/820126?lang=en" target="_blank"> Semantic Theory of Information</a>. Library and Information Science, 13(3), 101.</li>
          <li className='text-gray-700 mt-2'>&nbsp;<strong>Mansouri,A</strong>., &amp; Osareh, F. (2010). <a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://nastinfo.nlai.ir/article_214_0.html?lang=en.html" target="_blank"> Leading Scientific Countries of the Islamic World in the Web of Science Database</a>. National Studies on Librarianship and Information Organization, 21(1), 146– 169.</li>
          <li className='text-gray-700 mt-2'>&nbsp;<strong>Mansouri,A</strong>. (2009).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://rjnsq.sinaweb.net/article_99644.html" target="_blank"> National Identity in Text Books: A Content Analysis of Farsi Text Books of Elementary Level</a>. National Studies, 10(38), 27– 46.</li>
          <li className='text-gray-700 mt-2'><strong>Mansouri,A </strong>;Pashootanizadeh, M;&amp; Karami, N. A. (2009).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href=" https://www.sid.ir/fa/journal/ViewPaper.aspx?id=97558" target="_blank"> A Survey of Motivations Among Librarians for Scholarly Publishing</a>. Library and Information Scince, 12(246), 57– 74.</li>
          <li className='text-gray-700 mt-2'>&nbsp;Osareh, F; Bigdeli, Z; <strong> Mansouri,A</strong> ;&amp; Khasseh, A. (2009).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.researchgate.net/publication/228453011_A_digital_reference_desk_for_the_National_Library_of_Iran_A_prototype_based_on_content_analysis_of_the_digital_reference_desks_of_the_world's_national_libraries" target="_blank"> A Digital Reference Desk for the National Library of Iran: A Prototype Based on Content Analysis of the Digital Reference Desks of the World’s National libraries</a>. Reference Services Review, 37(2), 221– 233.</li>
          <li className='text-gray-700 mt-2'>Jokar,A;<strong>Mansouri,A</strong>; Pashootanizadeh, M;&amp; Shokri, M. (2008).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.magiran.com/paper/691886" target="_blank"> Citation Review of Articles Written in the Journal of Social Sciences and Humanities, Shiraz University (2001-2006)</a>. Social Sciences and Humanities, Shiraz University. </li>
          <li className='text-gray-700 mt-2'>&nbsp;Pashootanizadeh, M.,&amp;<strong> Mansouri,A</strong> . (2008).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://nastinfo.nlai.ir/article_345.html" target="_blank"> Library and Information Profession in 21st Century</a>. National Studies on Librarianship and Information Organization, 19(3), 137– 156.</li>
          <li className='text-gray-700 mt-2'>&nbsp;Pashootanizadeh, M., &amp;<strong> Mansouri,A</strong> .(2008).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href=" https://jipm.irandoc.ac.ir/article-1-6-en.html" target="_blank">Websites Evaluation by Children, Teenagers and Children Librarian</a>. Information Sciences and Technology, 24(1), 37– 50.</li>
          <li className='text-gray-700 mt-2'>&nbsp;Bigdeli, Z.,<strong> Mansouri,A</strong>., &amp; Pashootanizadeh, M. (2007).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://jipm.irandoc.ac.ir/article-1-64-en.html" target="_blank"> Examination of Viewpoints of Students at the Law and Political Sciences Faculty of Shiraz University Concerning Establishing Full-Text Persian Articles Database on Law and Political Sciences</a>. Information Sciences and Technology, 22(3), 33– 54.</li>
          <li className='text-gray-700 mt-2'><strong>Mansouri,A</strong> ; &amp; Pashootanizadeh, M. (2007).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="http://nastinfo.nlai.ir/article_439.html" target="_blank"> In Service Education for Librarians in the New Era</a>. National Studies on Librarianship and Information Organization, 18(2), 13– 24.</li>
          <li className='text-gray-700 mt-2'>&nbsp;Noroozi, A ;<strong>Mansouri,A</strong>;&amp; Hosseini, M. (2007).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.sid.ir/fa/journal/ViewPaper.aspx?ID=178331" target="_blank"> Population (Foxonomy): Organizing Knowledge Based on Collective wisdom</a>. Informatic, 5(1-2), 151– 166.</li>
          <li className='text-gray-700 mt-2'>&nbsp;Osareh, F;Bigdeli, Z; <strong> Mansouri,A</strong>.(2007).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href="https://www.sid.ir/fa/journal/ViewPaper.aspx?id=704661" target="_blank"> Providing a model for the digital reference desk of the Documentation Center and National Library of the Islamic Republic of Iran based on content analysis of the digital reference desks of the national libraries of the world</a>.Library and information, 10(3),125- 148. </li>
          <li className='text-gray-700 mt-2'>&nbsp;<strong>Mansouri,A</strong>.,&amp; Pashtoonizadeh, M. (2006).<a className='text-blue-900 hover:text-blue-800 hover:font-medium' href=" https://jipm.irandoc.ac.ir/article-1-71-en.html" target="_blank"> Importance of Digital Reference Desk in Special Libraries and Guidelines for Design of Digital Reference Desk Software with Emphasis on Reference Services</a>. Information Sciences and Technology, 21(4), 1– 18. </li>
        </ol>
      </div>
      
    </div>
  )
}

export default PublicationsPage